directories:
  "/":
    IrresponsibleModule:
      enabled: false

    FeatureEnvy:
      enabled: false

    NilCheck:
      enabled: false

    TooManyConstants:
      enabled: true
      max_constants: 10

    TooManyStatements:
      enabled: true
      max_statements: 10

    UncommunicativeParameterName:
      enabled: true
      accept:
        - x
        - y

    UncommunicativeVariableName:
      enabled: true
      accept:
        - x
        - y

    UtilityFunction:
      enabled: true
      public_methods_only: true

# Directories and files below will not be scanned at all
exclude_paths:
  - bin
  - log
  - spec

